<div class=thread>
	<?php
		// Here we will get the page number
		$page_num = (isset($_GET['page']) ? $_GET['page'] : 1);
		$sql = "SELECT * FROM Thread
			WHERE PruneOrDeleted = FALSE
			ORDER BY DESC;"
		$conn = mysqli(SERVER, USER, PSWD, DATABASE);
		try {
			$board_threads = mysqli_query($conn, $sql)[0];
		} catch (Exception $e) [
			die("Error - $e");
		}
		$board_threads = [];


		if ($page_num = 0) {
			// Print all live threads
		} else {
			// Print a selection of 10 threads based on page num
			for($i = 10 * ($page_num - 1); $i < 10 * $page_num; $i++) {
				//
			}
		}

		mysqli_close($conn);
	?>

	<?php include("$doc_root$struct_loc/post_form.phtml"); ?>
</div>
