<div class=board>
	<?php
		// Here we will get the page number
		$page_num = (isset($_GET['page']) ? $_GET['page'] : 1);
		$sql = "SELECT ThreadNo FROM Thread
			WHERE PruneOrDeleted=FALSE
			ORDER BY LastUpdate DESC";
		$conn = mysqli_connect(SERVER, USER, PSWD, DATABASE);
		try {
			$board_threads = mysqli_query($conn, $sql)->fetch_all();
		} catch (Exception $e) {
			die("Error - $e");
		}

		while (count($board_threads) < 10 * ($page_num - 1))
			$page_num--;

		echo "<div class=board-options>[ <a href=catalog>Catalog</a> / <a href=#bottom>Bottom</a> / <a href=# onclick=refreshBoards()>Refresh</a> ]</div><hr/>";
		
		if ($page_num == 0) {
			// Print all live threads
			foreach ($board_threads as $thread) {
				$thread_no	= $thread[0];
				include("$doc_root$struct_loc/thread.phtml");
			}
		} else {
			for($i = 10 * ($page_num - 1); $i < min(10 * $page_num, count($board_threads)); $i++) {
				$thread_no	= $board_threads[$i][0];
				include("$doc_root$struct_loc/thread.phtml");
			}
		}

		echo "<hr/><div class=board-options>[ <a href=catalog>Catalog</a> / <a href=#bottom>Bottom</a> / <a href=# onclick=refreshBoards()>Refresh</a> ]</div>";

		mysqli_close($conn);
	?>

	<?php include("$doc_root$struct_loc/post_form.phtml"); ?>
</div>
