<div class=board>
	<?php
		// Here we will get the page number
		$page_num = (isset($_GET['page']) ? $_GET['page'] : 1);
		$sql = "SELECT ThreadNo FROM Thread
			WHERE PruneOrDeleted=FALSE
			ORDER BY LastUpdate DESC";
		$conn = mysqli_connect(SERVER, USER, PSWD, DATABASE);
		try {
			$board_threads = mysqli_query($conn, $sql)->fetch_all();
		} catch (Exception $e) {
			die("Error - $e");
		}

		while (count($board_threads) < 10 * ($page_num - 1))
			$page_num--;

		if ($page_num == 0) {
			// Print all live threads
			echo "All";
			$thread_no	= 1;
			/*
			for ($i = 0; $i < count($board_threads); $i++) {
				$thread_no	= $board_threads[$i][0];
				include("$doc_root$struct_loc/thread.phtml");
			}
			*/
		} else {
			$thread_no	= 1;
			include("$doc_root/$struct_loc/thread.phtml");
			/*
			for($i = 10 * ($page_num - 1); $i < min(10 * $page_num, count($board_threads)); $i++) {
				echo "<hr/>$i<hr/>";
				$thread_no	= $board_threads[$i][0];
				include("$doc_root$struct_loc/thread.phtml");
			}
			*/
		}

		mysqli_close($conn);
	?>

	<?php include("$doc_root$struct_loc/post_form.phtml"); ?>
</div>
