<div id=<?php echo $thread_id; ?> class=catalog-item>
	<div class=preview-thumb></div>

	<div class=thread-stats>
		<span class=tooltip>
			R: <b><?php echo $num_replies; ?></b>
			<span class=tooltiptext>Replies</span>
		</span>
		/
		<span class=tooltip>
			M: <b><?php echo $num_replies; ?></b>
			<span class=tooltiptext>Media</span>
		</span>
	</div>

	<div class=catalog-title>
		<?php echo $title; ?>
	</div>

	<div class=preview-op>
		<?php echo $op_message; ?>
	</div>
</div>
