<?php
$conn = mysqli_connect(SERVER, USER, PSWD, DATABASE);

$boards = mysqli_query($conn, "SELECT * FROM Board;")->fetch_all();
?>
<div id=board-links>
	<?php
		foreach($boards as $board)
			echo "<a class=board-link href='/board/{$board[0]}/'>{$board[0]} - {$board[1]}</a>";
	?>
</div>

<?php
$promos = mysqli_query($conn, "SELECT Post.* FROM Post JOIN Thread ON Thread.ThreadNo=Post.PostID LIMIT 10")->fetch_all();
?>
<div id=promoted-threads>
	<?php
		foreach($promos as $promo) {
			$thread_id		= $promo[0];
			$media			= $promo[6];
			$thr_title		= $promo[3];
			$op_message		= $promo[7];

			$board			= mysqli_query($conn, "SELECT Board FROM Thread WHERE ThreadNo=$thread_id")->fetch_all()[0][0];
			$num_replies	= mysqli_query($conn, "SELECT COUNT(*) FROM Post WHERE ThreadID=$thread_id")->fetch_all()[0][0] - 1;
			$num_media		= mysqli_query($conn, "SELECT COUNT(*) FROM Post WHERE ThreadID=$thread_id AND NOT Media=0")->fetch_all()[0][0];
			$media_quer		= mysqli_query($conn, "SELECT Type FROM Media WHERE MediaID=$media")->fetch_all()[0][0];
			$media			= $media."_thumb.$media_quer";

			include("$doc_root/$struct_loc/catalog_item.phtml");
		}
	?>
</div>


<?php
// Collect the number of currently online users
$num_users		= $redis->dbSize();

// Collect the number of ripe and online threads
$num_threads	= mysqli_query($conn, "SELECT Count(ThreadNo) FROM Thread WHERE NOT PruneOrDeleted=1")->fetch_all()[0][0];

// Collect the total size of the hosted media
$media_size		= mysqli_query($conn, "SELECT COALESCE(SUM(m.Size), 0) AS TotalSize
	FROM Media m
	JOIN Post p ON m.MediaID=p.Media
	JOIN Thread t ON p.ThreadID=t.ThreadNo
	WHERE t.PruneOrDeleted=0")->fetch_all()[0][0];

if ($media_size >= 1_000_000_000) {
	if ($media_size >= 100_000_000_000) {
		$media_size = number_format($media_size / 1_000_000_000.0, '0', '.', '');
	} elseif ($media_size >= 10_000_000_000) {
		$media_size = number_format($media_size / 1_000_000_000.0, '1', '.', '');
	} else {
		$media_size = number_format($media_size / 1_000_000_000.0, '2', '.', '');
	}

	$media_size = $media_size."G";
} elseif ($media_size >= 1_000_000) {
	if ($media_size >= 100_000_000) {
		$media_size = number_format($media_size / 1_000_000.0, '0', '.', '');
	} elseif ($media_size >= 10_000_000) {
		$media_size = number_format($media_size / 1_000_000.0, '1', '.', '');
	} else {
		$media_size = number_format($media_size / 1_000_000.0, '2', '.', '');
	}

	$media_size = $media_size."M";
} elseif ($media_size >= 1_000) {
	if ($media_size >= 100_000) {
		$media_size = number_format($media_size / 1_000.0, '0', '.', '');
	} elseif ($media_size >= 10_000) {
		$media_size = number_format($media_size / 1_000.0, '1', '.', '');
	} else {
		$media_size = number_format($media_size / 1_000.0, '2', '.', '');
	}
	
	$media_size = $media_size."k";
}
$media_size = $media_size."B";

mysqli_close($conn);
?>
<div id=web-stats>
	<div class=div-title>Web Statistics</div>
	<br/>

	<span class=users-online>Number of Users: <b><?php echo $num_users; ?></b></span>
	<span class=thread-num>Number of Threads: <b><?php echo $num_threads; ?></b></span>
	<span class=media-size>Media: <b><?php echo $media_size; ?></b></span>
</div>
