<form class="form draggable" action="/php/handle_post.php" method="post" enctype="multipart/form-data">
	<p class=form-title>
		<?php echo ($uri[3] == "thread" ? "Reply to Thread" : "Make New Thread"); ?>
		<span class=close-form onclick=closeForm()>x</span>
	</p>
	<input type="text" name="make" value="<?php echo ($uri[2] ? "THREAD" : "POST") ?>" required hidden>
	<input type="text" name="board" value="<?php echo $board; ?>" required hidden>
	<?php
		if ($uri[3] == "thread")
			echo "<input type='text' name='thread_no' value='{$uri[4]}' required hidden>";
	?>

	<?php echo ($uri[3] == "thread" ? "" : "<input id=\"title\" type=\"text\" name=\"title\" placeholder=\"Title\">"); ?>

	<input id="name" type="text" name="name" placeholder="Name">

	<textarea id="message" type="text" name="message" placeholder="Message"></textarea>

	<input id="file" type="file" name="uploaded_file" <?php echo ($uri[3] == "thread" ? "" : "required"); ?>>

	<button type="submit">POST</button>
<form>
