<?php
// Message MarkDown

// Quote
$message = preg_replace('/^(>.*)($)/m', '<span class="quote">${1}</span>${2}', $message);

// Links:
// (text)[link]
$message = preg_replace('/\((.+?)\)\[(https?:\/\/)?(.+?)\]/', '<a href="${2}${3}">${1}</a>', $message);
// [link]
$message = preg_replace('/\[(https?:\/\/)?(.+?)\]/', '<a href="${1}${2}">${1}${2}</a>', $message);

// Breaklines
$message = preg_replace("/\n/", "<br/>", $message);

//$message = htmlspecialchars($message, ENT_QUOTES, 'UTF-8');
?>

<div class="post-container <?php echo ($op ? "op" : ""); ?>">
	<div class=post-top>
		<div class=post-info>
			<?php
				if ($op)
					echo "<span class=post-title>$title</span>";
			?>

			<span class=post-name><?php echo (($name == "") ? "Anonymous" : $name); ?></span>

			<span class=post-datetime><?php echo $datetime; ?></span>

			<span class=post-num>No.<?php echo $num; ?></span>

			<span class=menu-drop-down>▶</span>
		</div>

		<?php
			if (count($replies) > 0) {
				echo "<div class=replies>";
				foreach ($replies as $reply) { echo "<a href=#$reply>>>$reply</a>"; }
				echo "</div>";
			}
		?>
	</div>

	<div class=post-content>
		<?php
			if ($file != 0) {
				echo "<div class=file-info>
					<a class=filename href=\"media/$fileNum$fileType\">$fileName</a>
					<span class=file-dim-size>($fileDim) $formattedSize</span>
				</div>

				<div class=file>
					<img src=\"media/$fileNum$fileType\" />
				</div>";
			}
		?>

		<div class=message>
			<?php echo $message; ?>
		</div>
	</div>
</div>
