<div id=<?php echo $thread_no; ?> class=thread>
	<?php
		$conn = mysqli_connect(SERVER, USER, PSWD, DATABASE);
		$sql = "SELECT * FROM Post
			WHERE ThreadID = $thread_no";
		$thread = mysqli_query($conn, $sql)->fetch_all();

		$return_loc = implode("/", [$uri[0], $uri[1], $uri[2]]);

		if ($uri[3] == "thread") {
			echo "<div class=thread-options>[ <a href=$return_loc>Return</a> / <a href=$return_loc/catalog>Catalog</a> / <a href=#bottom>Bottom</a> / <a href=# onclick=refreshThread()>Refresh</a> ]</div><hr/>";

			foreach ($thread as $post) {
				$num		= $post[0];
				$op			= $post[1];
				$thread_no	= $post[2];
				$title		= $post[3];
				$name		= $post[4];
				$datetime	= $post[5];
				$file_num	= $post[6];
				$message	= $post[7];

				if ($file_num) {
					$file_data	= mysqli_query($conn, "SELECT * FROM Media WHERE MediaID = $file_num")->fetch_all();
					$file_name	= $file_data[0][1];
					$file_type	= $file_data[0][2];
					$file_size	= $file_data[0][3];
					$file_dim	= $file_data[0][4];
				}

				$replies	= mysqli_query($conn, "SELECT * FROM Reference WHERE Reference = $num")->fetch_all();
				include("$doc_root$struct_loc/post.phtml");
			}

			echo "<hr/><div class=thread-options>[ <a href=$return_loc>Return</a> / <a href=$return_loc/catalog>Catalog</a> / <a href=#top>Top</a> / <a href=# onclick=refreshThread()>Refresh</a> ]</div>";

			include("$doc_root$struct_loc/post_form.phtml");

			mysqli_close($conn);
		} else {
			$ori_post	= $thread[0];
			$num		= $ori_post[0];
			$op			= $ori_post[1];
			$thread_no	= $ori_post[2];
			$title		= $ori_post[3];
			$name		= $ori_post[4];
			$datetime	= $ori_post[5];
			$file_num	= $ori_post[6];
			$message	= $ori_post[7];

			if ($file_num) {
				$file_data	= mysqli_query($conn, "SELECT * FROM Media WHERE MediaID = $file_num")->fetch_all();
				$file_name	= $file_data[0][1];
				$file_type	= $file_data[0][2];
				$file_size	= $file_data[0][3];
				$file_dim	= $file_data[0][4];
			}
			$replies	= mysqli_query($conn, "SELECT * FROM Reference WHERE Reference=$num")->fetch_all();
			include("$doc_root$struct_loc/post.phtml");

			for($j = max(1, count($thread)-4); $j < count($thread); $j++) {
				$num		= $thread[$j][0];
				$op			= $thread[$j][1];
				$thread_no	= $thread[$j][2];
				$title		= $thread[$j][3];
				$name		= $thread[$j][4];
				$datetime	= $thread[$j][5];
				$file_num	= $thread[$j][6];
				$message	= $thread[$j][7];

				if ($file_num) {
					$file_data	= mysqli_query($conn, "SELECT * FROM Media WHERE MediaID = $file_num")->fetch_all();
					$file_name	= $file_data[0][1];
					$file_type	= $file_data[0][2];
					$file_size	= $file_data[0][3];
					$file_dim	= $file_data[0][4];
				}
				$replies	= mysqli_query($conn, "SELECT * FROM Reference WHERE Reference=$num")->fetch_all();
				include("$doc_root$struct_loc/post.phtml");
			}

			echo "<hr/> <span class=open-thread>[ <a href=thread/$thread_no>Open Thread</a> ] </span> <hr/>";
		}
	?>
</div>
