<div id=header>
	<?php include("$doc_root$static_loc/navi.phtml"); ?>

	<div id=web-banner>
		<img src=<?php echo "$web_ban_loc$web_banner"; ?> />
	</div>

	<div id=page-title><b><?php echo $title; ?></b></div>

	<hr/>

	<?php
		if (str_contains($_SERVER['REQUEST_URI'], 'thread'))
			echo "<div id=make-post onclick=openForm()>[ <a id=add-post href='#'>Make a Post</a> ]</div>";
		else if (str_contains($_SERVER['REQUEST_URI'], 'board'))
			echo "<div id=make-thread onclick=openForm()>[ <a id=add-thread href='#'>Make a Thread</a> ]</div>";
	?>

	<div id=changelog>
		<?php
			$ch_lo = file("$doc_root/CHANGE.LOG", FILE_SKIP_EMPTY_LINES);
			for ($i = 1; $i < 4; $i++)
				if (sizeof($ch_lo) - $i >= 0)
					echo "<span class=log>{$ch_lo[sizeof($ch_lo) - $i]}</span>";
		?>
	</div>

	<?php
		if (str_contains($_SERVER['REQUEST_URI'], 'board')) {
			echo "
				<div id=board-promo>
					<img src=$board_ban_loc$board_banner />
				</div>";
		}
	?>

	<br/>

	<div id=top-banner><a class=ad-banner href=<?php echo $ad_href; ?>><img id=add-img src=<?php echo "$ad_ban_loc$ad_banner"; ?> /></a></div>

	<hr/>
</div>
