<head>
	<?php 
		// Title Generation
		$uri_loc = $_SERVER['REQUEST_URI'];
		if (str_contains($uri_loc, 'thread')) {
			$thread_no = explode('/', $uri_loc)[4];
			$conn = mysqli_connect(SERVER, USER, PSWD, DATABASE);
			$thr_tit = mysqli_query($conn, "SELECT Title FROM Post WHERE PostID = $thread_no")->fetch_all()[0][0];
			mysqli_close($conn);
			$title = "$title - $thr_tit";
		}
		include("$doc_root$static_loc/head.phtml");
	?>
</head>

<body>
	<?php
		include("$doc_root$static_loc/header.phtml");

		echo "<div id=content-wrap>";
			$uri_loc = $_SERVER['REQUEST_URI'];
			if (str_contains($uri_loc, 'thread')) {
				$thread_no	= explode('/', $uri_loc)[4];
				include("$doc_root$struct_loc/thread.phtml");
			} else if (str_contains($uri_loc, 'catalog')) {
				include("$doc_root$struct_loc/catalog.phtml");
			} else if (str_contains($uri_loc, 'board')) {
				include("$doc_root$struct_loc/board.phtml");
			} else if (str_contains($uri_loc, 'janny-station')) {
				include("$doc_root$struct_loc/janny.phtml");
			} else if ($err == 404) {
				include("$doc_root$struct_log/404.phtml");
			} else if ($err == 500) {
				echo "<span class=error>The programmer is having a bad day</span>";
			} else {
				include("$doc_root$struct_loc/home.phtml");
			}
		echo "</div>";
	
		include("$doc_root$static_loc/footer.phtml");
	?>
</body>
