<head>
	<?php 
		// Title Generation
		$uri_loc = $_SERVER['REQUEST_URI'];
		if (str_contains($uri_loc, 'thread')) {
			$thread_no = explode('/', $uri_loc)[4];
			$conn = mysqli_connect(SERVER, USER, PSWD, DATABASE);
			$thr_tit = mysqli_query($conn, "SELECT Title FROM Post WHERE PostID = $thread_no")->fetch_all()[0][0];
			mysqli_close($conn);
			$title = "$thr_tit";
		} elseif (str_contains($uri_loc, 'catalog')) {
			$title = "$title - Catalog";
		} else if (str_contains($uri_loc, 'janny-station')) {
			$title = "/Janny Station/";
		}
		include("$doc_root$static_loc/head.phtml");
	?>
</head>

<body>
	<?php
		include("$doc_root$static_loc/header.phtml");

		echo "<div id=content-wrap>";
			$uri_loc = $_SERVER['REQUEST_URI'];
			if (str_contains($uri_loc, 'thread')) {
				$thread_no	= explode('/', $uri_loc)[4];
				include("$doc_root$struct_loc/thread.phtml");
			} else if (str_contains($uri_loc, 'catalog')) {
				include("$doc_root$struct_loc/catalog.phtml");
			} else if (str_contains($uri_loc, 'board')) {
				include("$doc_root$struct_loc/board.phtml");
			} else if (str_contains($uri_loc, 'janny-station')) {
				include("$doc_root$struct_loc/janny.phtml");
			} else if ($err == 404) {
				$lost_images = scandir("$doc_root/assets/images/lost/");
				$lost_images = array_splice($lost_images, 2);
				$lost_image = $lost_images[floor(rand(0, sizeof($lost_images)-1))];

				echo "<div class=error-page>
					<h2 class=error>Couldn't find that, sorry</h2>
					<img class=lost-image src='assets/images/lost/$lost_image' />
					<div class=escape-nav>[ <a href=/>Home</a> ]</div>
				</div>";
			} else if ($err == 500) {
				echo "<span class=error>The programmer is having a bad day</span>";
			} else {
				include("$doc_root$struct_loc/home.phtml");
			}
		echo "</div>";
	
		include("$doc_root$static_loc/footer.phtml");
	?>
</body>
