<head>
	<?php include("$doc_root$static_loc/head.phtml"); ?>
</head>

<body>
	<?php
		include("$doc_root$static_loc/header.phtml");

		$uri_loc = $_SERVER['REQUEST_URI'];
		if (str_contains($uri_loc, 'thread'))
			include("$doc_root$struct_loc/thread.phtml");
		else if (str_contains($uri_loc, 'catalog'))
			include("$doc_root$struct_loc/catalog.phtml");
		else if (str_contains($uri_loc, 'board'))
			include("$doc_root$struct_loc/board.phtml");
		else if (str_contains($uri_loc, 'janny-station'))
			include("$doc_root$struct_loc/janny.phtml");
		else
			include("$doc_root$struct_loc/home.phtml");
	
		include("$doc_root$static_loc/footer.phtml");
	?>
</body>
